version: "2.4"
services:

  dotnetsdk:
    container_name: mvp-dotnetsdk
    image: ${MVP_DOCKER_REGISTRY}mvp-dotnetsdk:${SITECORE_VERSION}
    build:
      context: ./docker/build/dotnetsdk
      args:
        BUILD_IMAGE: ${SOLUTION_BUILD_IMAGE}
        NETCORE_BUILD_IMAGE: ${NETCORE_BUILD_IMAGE}
    scale: 0

  solutionBuildOutput:
    container_name: mvp-solution
    image: ${MVP_DOCKER_REGISTRY}mvp-solution:${SITECORE_VERSION}
    build:
      context: ./
      dockerfile: ./docker/build/solution/Dockerfile
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION}
        BASE_IMAGE: ${SOLUTION_BASE_IMAGE}
        BUILD_IMAGE: ${MVP_DOCKER_REGISTRY}mvp-dotnetsdk:${SITECORE_VERSION}
    depends_on:
      - dotnetsdk
    scale: 0

  mvp-rendering:
    container_name: mvp-rendering
    image: ${MVP_DOCKER_REGISTRY}mvp-rendering:${SITECORE_VERSION}
    build:
      context: ./docker/build/rendering
      target: ${BUILD_CONFIGURATION}
      args:
        DEBUG_BASE_IMAGE: ${MVP_DOCKER_REGISTRY}mvp-dotnetsdk:${SITECORE_VERSION}
        RELEASE_BASE_IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1
        SOLUTION_IMAGE: ${MVP_DOCKER_REGISTRY}mvp-solution:${SITECORE_VERSION}
    depends_on:
      - solutionBuildOutput
  
  id:
    image: ${MVP_DOCKER_REGISTRY}mvp-id:${SITECORE_VERSION}
    build:
      context: ./docker/build/id
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${ID_IMAGE}:${SITECORE_VERSION}
        SOLUTION_IMAGE: ${MVP_DOCKER_REGISTRY}mvp-solution:${SITECORE_VERSION}
    depends_on:
      - solutionBuildOutput

  cd:
    image: ${MVP_DOCKER_REGISTRY}mvp-cd:${SITECORE_VERSION}
    build:
      context: ./docker/build/cd
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${CD_IMAGE}:${SITECORE_VERSION}
        SOLUTION_IMAGE: ${MVP_DOCKER_REGISTRY}mvp-solution:${SITECORE_VERSION}
        TOOLS_RESOURCES_IMAGE: ${TOOLS_RESOURCES_IMAGE}
        JSS_RESOURCES_IMAGE: ${JSS_RESOURCES_IMAGE}
    depends_on:
      - solutionBuildOutput

  cm:
    image: ${MVP_DOCKER_REGISTRY}mvp-cm:${SITECORE_VERSION}
    build:
      context: ./docker/build/cm
      args:
        BASE_IMAGE: ${SITECORE_DOCKER_REGISTRY}${CM_IMAGE}:${SITECORE_VERSION}
        SOLUTION_IMAGE: ${MVP_DOCKER_REGISTRY}mvp-solution:${SITECORE_VERSION}
        TOOLS_RESOURCES_IMAGE: ${TOOLS_RESOURCES_IMAGE}
        DEVEX_RESOURCES_IMAGE: ${DEVEX_RESOURCES_IMAGE}
        JSS_RESOURCES_IMAGE: ${JSS_RESOURCES_IMAGE}
    depends_on:
      - solutionBuildOutput
