apiVersion: v1
kind: Service
metadata:
  name: mvp-rendering
spec:
  selector:
    app: mvp-rendering
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mvp-rendering
  labels:
    app: mvp-rendering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mvp-rendering
  template:
    metadata:
      labels:
        app: mvp-rendering
    spec:
      nodeSelector:
        kubernetes.io/os: windows
      containers:
      - name: sitecore-xm1-rendering
        image: mvpsitev2.azurecr.io/mvp-rendering:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Release
        - name: ASPNETCORE_URLS
          value: http://*:80
        - name: Sitecore__InstanceUri
          value: http://mvp-cm
        - name: Sitecore__RenderingHostUri
          value: https://$(STAGING_HOST)/
        - name: Sitecore__EnableExperienceEditor
          value: "true"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
            httpHeaders:
            - name: X-Kubernetes-Probe
              value: Liveness
          timeoutSeconds: 60
          periodSeconds: 30
          failureThreshold: 3
      imagePullSecrets:
      - name: regcred